---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: bonzofenix/ci-tools
    tag: edge

params:
  GOVC_URL:
  GOVC_INSECURE:
  GOVC_USERNAME:
  GOVC_PASSWORD:
  GOVC_FOLDER:
  GOVC_VM_NAME:
  VM_IP:
  VM_ADMIN_USERNAME:
  VM_ADMIN_PASSWORD:

inputs:
  - name: pipeline
  - name: config
  - name: lgpo-zip
  - name: stembuild

run:
  path: pipeline/ci/scripts/deploy-windows-stemcell.sh
